# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tesla

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Message(object):
    NONE = 0
    FbReserved1 = 1
    FbReserved2 = 2
    FbReserved3 = 3
    FlatbuffersStream = 4
    FlatbuffersStreamAck = 5


class FbReserved1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FbReserved1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFbReserved1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FbReserved1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FbReserved1Start(builder):
    builder.StartObject(0)

def FbReserved1End(builder):
    return builder.EndObject()



class FbReserved2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FbReserved2()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFbReserved2(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FbReserved2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FbReserved2Start(builder):
    builder.StartObject(0)

def FbReserved2End(builder):
    return builder.EndObject()



class FbReserved3(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FbReserved3()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFbReserved3(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FbReserved3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FbReserved3Start(builder):
    builder.StartObject(0)

def FbReserved3End(builder):
    return builder.EndObject()



class FlatbuffersStream(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatbuffersStream()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlatbuffersStream(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FlatbuffersStream
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlatbuffersStream
    def CreatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FlatbuffersStream
    def SenderId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FlatbuffersStream
    def SenderIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FlatbuffersStream
    def SenderIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatbuffersStream
    def SenderIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # FlatbuffersStream
    def Payload(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FlatbuffersStream
    def PayloadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FlatbuffersStream
    def PayloadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatbuffersStream
    def PayloadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # FlatbuffersStream
    def DeviceType(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FlatbuffersStream
    def DeviceTypeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FlatbuffersStream
    def DeviceTypeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatbuffersStream
    def DeviceTypeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # FlatbuffersStream
    def DeviceId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FlatbuffersStream
    def DeviceIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FlatbuffersStream
    def DeviceIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatbuffersStream
    def DeviceIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # FlatbuffersStream
    def DeliveredAtEpochMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def FlatbuffersStreamStart(builder):
    builder.StartObject(6)

def FlatbuffersStreamAddCreatedAt(builder, createdAt):
    builder.PrependUint32Slot(0, createdAt, 0)

def FlatbuffersStreamAddSenderId(builder, senderId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(senderId), 0)

def FlatbuffersStreamStartSenderIdVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def FlatbuffersStreamAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def FlatbuffersStreamStartPayloadVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def FlatbuffersStreamAddDeviceType(builder, deviceType):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(deviceType), 0)

def FlatbuffersStreamStartDeviceTypeVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def FlatbuffersStreamAddDeviceId(builder, deviceId):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def FlatbuffersStreamStartDeviceIdVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def FlatbuffersStreamAddDeliveredAtEpochMs(builder, deliveredAtEpochMs):
    builder.PrependUint64Slot(5, deliveredAtEpochMs, 0)

def FlatbuffersStreamEnd(builder):
    return builder.EndObject()



class FlatbuffersStreamAck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatbuffersStreamAck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlatbuffersStreamAck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FlatbuffersStreamAck
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FlatbuffersStreamAckStart(builder):
    builder.StartObject(0)

def FlatbuffersStreamAckEnd(builder):
    return builder.EndObject()



class FlatbuffersEnvelope(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatbuffersEnvelope()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlatbuffersEnvelope(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FlatbuffersEnvelope
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlatbuffersEnvelope
    def Txid(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FlatbuffersEnvelope
    def TxidAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FlatbuffersEnvelope
    def TxidLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatbuffersEnvelope
    def TxidIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # FlatbuffersEnvelope
    def Topic(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FlatbuffersEnvelope
    def TopicAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FlatbuffersEnvelope
    def TopicLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatbuffersEnvelope
    def TopicIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # FlatbuffersEnvelope
    def MessageType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FlatbuffersEnvelope
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # FlatbuffersEnvelope
    def MessageId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FlatbuffersEnvelope
    def MessageIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FlatbuffersEnvelope
    def MessageIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatbuffersEnvelope
    def MessageIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def FlatbuffersEnvelopeStart(builder):
    builder.StartObject(5)

def FlatbuffersEnvelopeAddTxid(builder, txid):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(txid), 0)

def FlatbuffersEnvelopeStartTxidVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def FlatbuffersEnvelopeAddTopic(builder, topic):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(topic), 0)

def FlatbuffersEnvelopeStartTopicVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def FlatbuffersEnvelopeAddMessageType(builder, messageType):
    builder.PrependUint8Slot(2, messageType, 0)

def FlatbuffersEnvelopeAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def FlatbuffersEnvelopeAddMessageId(builder, messageId):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(messageId), 0)

def FlatbuffersEnvelopeStartMessageIdVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def FlatbuffersEnvelopeEnd(builder):
    return builder.EndObject()



